### ISSUE TITLE
Fixing crossfade issues

### ISSUE THREAD

**Issue by aldeed** [percolatestudio/meteor-momentum#23]
I'm using momentum around a couple `Template.dynamic`s. The "fade" option is glitchy in this case because the new element is added to the DOM before the old is removed. I don't think a true crossfade is possible unless both elements are absolutely positioned?

I solved my issue by overriding the fade to wait until hiding is done before showing:

```js
Momentum.registerPlugin('fade', function(options) {
  return {
    insertElement: function(node, next) {
      $(node)
        .hide()
        .insertBefore(next)
        .velocity('fadeIn', {delay: 500});
    },
    removeElement: function(node) {
      $(node).velocity('fadeOut', function() {
        $(this).remove();
      });
    }
  }
});
```

Other than posting this for the benefit of others, I'm also wondering if anyone can think of a better solution and/or if this type of fade should be a built-in option. Could also have achieved this with css I suppose.

**Comment by zol** [comment]
Hey @aldeed . Not sure what issue you're addressing, could you post a reproduction? In the example, replacing the `growl` plugin with the `fade` one works ok - it may not be the nicest animation but it isn't glitchy.

**Comment by aldeed** [comment]
@zol see [here](http://meteorpad.com/pad/Hj8mH3jYpm63Q2GyG/Momentum%20Fade%20Glitch). You can uncomment the fix code to see how it changes.

I tried with growl and it has the same problem.

**Comment by zol** [comment]
Ahh, I see, thanks @aldeed . The real issue here is that the fade plugin would need to know whether its doing an element replacement or not. The code you linked to is a reasonable solution to your specific problem but its not really *correct* as a general solution. Any inserted element's animation would be delayed by 500ms.

I don't think we can find out from `uihooks` whether a replacement is happening.

In any case, momentum is still very much an idea rather than a package that is being maintained for public consumption. Users of the package are encouraged to write their own plugins to implement logic specific to their applications. I'm still not convinced that putting more logic and complexity in the plugins momentum ships with to address a larger range of real world cases is a worthwhile endeavor.

**Comment by aldeed** [comment]
Yeah, I think I agree with that. Just wanted to make sure I wasn't missing something. Thanks!
